FROM python:3.10-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /appli
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

# Copy app code
COPY apps ./apps/

# Place executables in the environment at the front of the path
ENV PATH="/appli/.venv/bin:$PATH"

# Run the worker in daemon mode by default
CMD ["python", "apps/worker.py", "--daemon"]
