FROM python:3.10-slim
RUN pip install --upgrade pip
RUN pip install --no-cache-dir gunicorn
COPY requirements-api.txt /
RUN pip install --no-cache-dir -r /requirements-api.txt

WORKDIR /appli
COPY start.py config.py ./
COPY apps ./apps/
COPY templates ./templates/

CMD ["/bin/bash", "-c", "gunicorn --workers 2 --timeout 60 --bind 0.0.0.0:9001 start:app"]
