FROM python:3.10-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /appli
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-progress

COPY start.py config.py ./
COPY apps ./apps/
COPY templates ./templates/
COPY tests ./tests/

# Place executables in the environment at the front of the path
ENV PATH="/appli/.venv/bin:$PATH"

CMD ["/bin/bash", "-c", "gunicorn --workers 2 --timeout 600 --bind 0.0.0.0:9001 start:app"]
