FROM python:3.10-slim
RUN pip install --upgrade pip
COPY requirements-cacher.txt /
RUN pip install --no-cache-dir -r /requirements-cacher.txt

WORKDIR /appli
COPY cache.py config.py ./
COPY apps ./apps/

CMD ["/bin/bash", "-c", "python3 cache.py"]
