[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ws-availability"
version = "1.1.0b1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.0",
    "gunicorn>=23.0",
    "obspy>=1.4.1",
    "pymongo>=4.6",
    "redis>=5.0",
    "requests>=2.32",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.12.0",
    "sentry-sdk[flask]>=2.0.0",
    "apscheduler>=3.11.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pyyaml>=6.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["apps*"]
namespaces = false

[tool.setuptools.package-data]
"*" = ["views/*", "templates/*"]
